spring.application.name=financewave-transaction-service
server.port=8083

# LOAD ENV
spring.config.import=optional:file:.env

# DB
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

account.service.url=http://localhost:8082
beneficiary.service.url=http://localhost:8084

# =========================
# FEATURE FLAGS
# =========================
feature.fraud.check=true
feature.notifications=false
feature.audit.enabled=true
#account.service.url=http://localhost:8082/accounts

#account.service.url=${ACCOUNT_SERVICE_URL}

#jwt.secret=N2JhZjU4NjQyYmMzYjE5ZDQ2YTkzM2EyMDEyNjVkNjFiMmY4ZTEyNWI0YjZlYjYzNzU0NTE2ZjM1NWMzYzVjMA==
#jwt.expiration=1800000