spring.application.name=financewave-beneficiary-service
spring.config.import=optional:file:.env
server.port=8084

#spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}


spring.datasource.url=jdbc:postgresql://localhost:5432/beneficiary_db
spring.datasource.username=postgres
spring.datasource.password=admin
jwt.secret=N2JhZjU4NjQyYmMzYjE5ZDQ2YTkzM2EyMDEyNjVkNjFiMmY4ZTEyNWI0YjZlYjYzNzU0NTE2ZjM1NWMzYzVjMA==
jwt.expiration=1800000

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.core.env=DEBUG